[package]
name = "chip8-wasm"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
description = ""
license = "Apache-2.0/MIT"
readme = "./README.md"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
wasm-bindgen = "0.2.89"
chip8 = { path = "../../chip8" }
